/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SchedulingSystem;

import Course.*;

/**
 * JFrame that allows user to add courses to SchedulingSystem
 * @author Kevin Wang
 */
public class AddCourseWindow extends javax.swing.JFrame {
    private SchedulingSystem schedulingSystem;
    private boolean addCourseButtonPressed;

    /**
     * Creates new form AddCourseWindow
     */
    public AddCourseWindow() {
        initComponents();
        addCourseButtonPressed = false;
    }
    
    /**
     * Constructor that should be used to create a new form AddCourseWindow
     * @param schedulingSystem SchedulingSystem object that is being used throughout the system
     */
    public AddCourseWindow(SchedulingSystem schedulingSystem) {
        initComponents();
        this.schedulingSystem = schedulingSystem;
        addCourseButtonPressed = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        courseNameTextField = new javax.swing.JTextField();
        enterCourseNameLabel = new javax.swing.JLabel();
        addCourseButton = new javax.swing.JButton();
        numberOfSectionsTextField = new javax.swing.JTextField();
        numberOfSectionsLabel = new javax.swing.JLabel();
        deptNameLabel = new javax.swing.JLabel();
        deptNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(438, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 152;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        getContentPane().add(courseNameTextField, gridBagConstraints);

        enterCourseNameLabel.setText("Enter Course Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 70, 0, 0);
        getContentPane().add(enterCourseNameLabel, gridBagConstraints);

        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 76, 66);
        getContentPane().add(addCourseButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 4, 0, 0);
        getContentPane().add(numberOfSectionsTextField, gridBagConstraints);

        numberOfSectionsLabel.setText("Number of Sections:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 70, 0, 0);
        getContentPane().add(numberOfSectionsLabel, gridBagConstraints);

        deptNameLabel.setText("Department Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(101, 70, 0, 0);
        getContentPane().add(deptNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 152;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(98, 4, 0, 0);
        getContentPane().add(deptNameTextField, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler that adds Course object to SchedulingSystem from info inputted
     * @param evt 
     */
    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        addCourseButtonPressed = true;
        
        String deptName = deptNameTextField.getText();
        String courseName = courseNameTextField.getText();
        int numOfSections = Integer.parseInt(numberOfSectionsTextField.getText());
        Course newCourse = new Course(deptName, courseName);
        
        //adds Sections
        AddSectionsWindow sectionWindow = new AddSectionsWindow(newCourse, numOfSections, schedulingSystem);
        sectionWindow.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_addCourseButtonActionPerformed

    /**
     * Event handler that handles the closing of the AddCourseWindow. It returns back to the adminWindow
     * @param evt 
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(!addCourseButtonPressed){
            AdministratorWindow adminWindow = new AdministratorWindow(schedulingSystem);
            adminWindow.setVisible(true);
        } 
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look aaddCourseButtone (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JTextField courseNameTextField;
    private javax.swing.JLabel deptNameLabel;
    private javax.swing.JTextField deptNameTextField;
    private javax.swing.JLabel enterCourseNameLabel;
    private javax.swing.JLabel numberOfSectionsLabel;
    private javax.swing.JTextField numberOfSectionsTextField;
    // End of variables declaration//GEN-END:variables
}
