/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SchedulingSystem;

import Course.Course;
import Course.Section;

/**
 *
 * @author wanga
 */
public class AddSectionsWindow extends javax.swing.JFrame {
    private Course workingCourse;
    private int numOfSections;
    private int currentSectionNum;
    private SchedulingSystem schedulingSystem = null;
    
    /**
     * Creates new form addLectureWindow
     */
    public AddSectionsWindow() {
        initComponents();
    }
    
    public AddSectionsWindow(Course newCourse, int numOfSections, SchedulingSystem schedulingSystem){
        initComponents();
        workingCourse = newCourse;
        this.numOfSections = numOfSections;
        currentSectionNum = 1;
        currentSection.setText("Current Section Num being added: " + currentSectionNum + " out of " + numOfSections + " Sections.");
        this.schedulingSystem = schedulingSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sectionNameLabel = new javax.swing.JLabel();
        sectionNameTextField = new javax.swing.JTextField();
        dateTimeLabel = new javax.swing.JLabel();
        addSectionButton = new javax.swing.JButton();
        dateTimeTextField = new javax.swing.JTextField();
        roomLabel = new javax.swing.JLabel();
        roomTextField = new javax.swing.JTextField();
        instructorLabel = new javax.swing.JLabel();
        instructorTextField = new javax.swing.JTextField();
        currentSection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        sectionNameLabel.setText("Section Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 205, 0, 0);
        getContentPane().add(sectionNameLabel, gridBagConstraints);

        sectionNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionNameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 204);
        getContentPane().add(sectionNameTextField, gridBagConstraints);

        dateTimeLabel.setText("Date/Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 205, 0, 0);
        getContentPane().add(dateTimeLabel, gridBagConstraints);

        addSectionButton.setText("Add Section");
        addSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSectionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 205, 98, 0);
        getContentPane().add(addSectionButton, gridBagConstraints);

        dateTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTimeTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 4, 0, 204);
        getContentPane().add(dateTimeTextField, gridBagConstraints);

        roomLabel.setText("Room:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 205, 0, 0);
        getContentPane().add(roomLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 204);
        getContentPane().add(roomTextField, gridBagConstraints);

        instructorLabel.setText("Instructor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 205, 0, 0);
        getContentPane().add(instructorLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 3, 0, 204);
        getContentPane().add(instructorTextField, gridBagConstraints);

        currentSection.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 205, 0, 204);
        getContentPane().add(currentSection, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSectionButtonActionPerformed
        /*Insert info
        Then clear data as many times as there are sections and update counter so that I know how many more sections to add data for
        */
        if(currentSectionNum + 1 <= numOfSections){
            
            //Updates which section number the admin is currently adding to the working course
            currentSection.setText("Current Section Num being added: " + (currentSectionNum++) + " out of " + numOfSections + " Sections.");
            
            //Gets info
            String sectionName = sectionNameTextField.getText();
            String dateTime = dateTimeTextField.getText();
            String room = roomTextField.getText();
            String instructor = instructorTextField.getText();
            
            Section newSection = new Section(sectionName, dateTime, room, instructor);
            workingCourse.addSection(newSection);
            
            //Clears inputs
            sectionNameTextField.setText("");
            dateTimeTextField.setText("");
            roomTextField.setText("");
            instructorTextField.setText("");
        }
        
        //Add Course to Scheduling System
        System.out.println("YEET");
        schedulingSystem = new SchedulingSystem();
        schedulingSystem.addCourse(workingCourse);//nullPointerException thrown here
        
        
        //Close window
        
        
    }//GEN-LAST:event_addSectionButtonActionPerformed

    private void sectionNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionNameTextFieldActionPerformed

    private void dateTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTimeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSectionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSectionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSectionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSectionsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSectionsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSectionButton;
    private javax.swing.JLabel currentSection;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JTextField dateTimeTextField;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JTextField instructorTextField;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JTextField roomTextField;
    private javax.swing.JLabel sectionNameLabel;
    private javax.swing.JTextField sectionNameTextField;
    // End of variables declaration//GEN-END:variables
}
